import type {Metadata} from 'next'
import './globals.scss'
import Header from "@/app/ui/header/header";
import Footer from "@/app/ui/footer/footer";
import Svg from "@/app/ui/svg";
import { register } from 'swiper/element/bundle';
import {poppins} from "@/app/ui/fonts";

register();
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <>
            <head>
                <title>Angels Road inc</title>
                <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
                <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
                <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
            </head>
            <html lang="en">
            <body className={poppins.className}>
            <Svg/>
            <Header/>
            {children}
            <Footer/>
            </body>
            </html>
        </>
    )
}
