import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.scss'
import Header from "@/app/ui/header/header";
import {ThemeProvider} from "next-themes";
import Footer from "@/app/ui/footer/footer";
import Svg from "@/app/ui/svg";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <Svg />
        <body className={inter.className}>
            <Header/>
                {children}
            <Footer />
        </body>
        </html>
    )
}
